name:                linnet
version:             0.1.0.0
github:              haskell-linnet/linnet
license:             Apache
author:              Sergey Kolbasov
maintainer:          whoisliar@gmail.com
copyright:           2019 Sergey Kolbasov
category:            linnet
synopsis:            Lightweight library for building HTTP API

extra-source-files:
  - README.md
  - LICENSE

description:         Please see the documentation at <http://linnet.io>

dependencies:
  - base >= 4.7 && < 5
  - io-streams
  - bytestring
  - wai
  - warp
  - http-types
  - text
  - utf8-string
  - either
  - transformers
  - bytestring-conversion
  - case-insensitive
  - exceptions
  - uri-encode
  - mtl

library:
  source-dirs: src

tests:
  linnet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - linnet
      - hspec
      - QuickCheck
      - quickcheck-instances
      - quickcheck-classes