name:                linnet
version:             0.1.0
github:              "https://github.com/haskell-linnet/linnet"
license:             "Apache"
author:              "Sergey Kolbasov"
maintainer:          "whoisliar@gmail.com"
copyright:           "2019 Sergey Kolbasov"

extra-source-files:
  - README.md
  - LICENSE

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/haskell-linnet/linnet#readme>

dependencies:
  - base >= 4.7 && < 5
  - io-streams
  - bytestring
  - wai
  - warp
  - http-types
  - text
  - utf8-string
  - either
  - transformers-base
  - transformers
  - bytestring-conversion
  - case-insensitive
  - exceptions

library:
  source-dirs: src

tests:
  linnet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - linnet
      - hspec
      - QuickCheck
      - quickcheck-instances