name:                linnet-conduit
version:             0.4.0.0
github:              haskell-linnet/linnet
license:             Apache
author:              Sergey Kolbasov
maintainer:          whoisliar@gmail.com
copyright:           2019 Sergey Kolbasov
category:            linnet
synopsis:            Conduit-backed support for streaming in Linnet

extra-source-files:
  - README.md
  - LICENSE

description:         Please see the documentation at <http://linnet.io>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - wai
  - warp
  - http-types
  - conduit
  - linnet

library:
  source-dirs: src

tests:
  linnet-conduit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - linnet-conduit
      - hspec
      - QuickCheck
      - quickcheck-instances
      - quickcheck-classes
