name:                linnet-benchmarks
version:             0.4.0.0
github:              haskell-linnet/linnet
license:             Apache
author:              Sergey Kolbasov
maintainer:          whoisliar@gmail.com
copyright:           2019 Sergey Kolbasov
category:            linnet
synopsis:            Linnet benchmarks

extra-source-files:
  - README.md
  - LICENSE

description:         Please see the documentation at <http://linnet.io>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - wai
  - warp
  - http-types
  - text
  - either
  - transformers
  - bytestring-conversion
  - case-insensitive
  - exceptions
  - uri-encode
  - mtl
  - http-media
  - time
  - criterion
  - linnet >= 0.4.0.1
  - linnet-aeson
  - aeson
  - deepseq
  - random

benchmarks:
  linnet-benchmarks:
    main:                Benchmarks.hs
    source-dirs:         benchmarks
    ghc-options:
      - -O2
      - -threaded